#spring:
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      authentication-database: admin
#      username: admin
#      password: admin
#      database: shopping_cart

spring:
    datasource:
      url:
        jdbc:oracle:thin:@localhost:1521:xe
      username:
        <your username>
      password:
        <your password>
      driver-class-oracle:
        jdbc:
          driver:
            OracleDriver