#spring:
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      authentication-database: admin
#      username: admin
#      password: admin
#      database: shopping_cart

#spring:
#    datasource:
#      url:
#        jdbc:oracle:thin:@192.9.200.210:1521:oradesa
#      username:
#        AFPCONFIABE
#      password:
#        AFPCONFIABE
#      driver-class-oracle:
#        jdbc:
#          driver:
#            OracleDriver

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect