/*
   DROP TABLE IF EXISTS ADM_PERSONA;
   CREATE TABLE "ADM_PERSONA"
      (	"NUM_LICENCIA" NUMBER NOT NULL,
   	"COD_PERSONA" NUMBER(8,0) NOT NULL,
   	"NOMBRES" VARCHAR2(200 ) NOT NULL,
   	"COD_TIPO_EMPLEO" VARCHAR2(8 ) NOT NULL,
   	"CATEGORIA" VARCHAR2(1 ) NOT NULL,
   	"NOMBRE1" VARCHAR2(100 ) NOT NULL,
   	"NOMBRE2" VARCHAR2(50 ) NOT NULL,
   	"APELLIDOPATERNO" VARCHAR2(20 ) NOT NULL,
   	"APELLIDOMATERNO" VARCHAR2(20 ) NOT NULL,
   	"COD_ESTADO_PERSONA" VARCHAR2(8 ) NOT NULL,
   	"FECHA_NACIMIENTO" DATE NOT NULL,
   	"COD_PAIS" VARCHAR2(10 ) NOT NULL,
   	"PAIS_LOCAL" VARCHAR2(1 ) NOT NULL,
   	"AUD_VERSION" NUMBER(10,0) NOT NULL);

   DROP TABLE IF EXISTS ADM_PERSONA_IDENTIFICACION;
   CREATE TABLE "ADM_PERSONA_IDENTIFICACION"
      (	"NUM_LICENCIA" NUMBER,
   	"COD_PERSONA" NUMBER(8,0) NOT NULL ,
   	"COD_TIPO_IFICACION" VARCHAR2(8 BYTE) NOT NULL ,
   	"IDENTIFICACION" VARCHAR2(30 BYTE) NOT NULL ,
   	"PREFERIDO" VARCHAR2(1 BYTE) NOT NULL ,
   	"FECHA_CADUCIDAD" DATE,
   	"AUD_VERSION" NUMBER(10,0),
   	 CONSTRAINT "SYS_C_SNAP$_5443IDEXPER_PK" PRIMARY KEY ("COD_PERSONA", "COD_TIPO_IFICACION"));

 DROP TABLE IF EXISTS ADM_CLIENTE;
   CREATE TABLE "ADM_CLIENTE"
      (	"NUM_LICENCIA" NUMBER(10,0),
   	"COD_EMPRESA" VARCHAR2(8 BYTE),
   	"COD_PRODUCTO" VARCHAR2(8 BYTE),
   	"COD_PERSONA" NUMBER(8,0),
   	"TIPO_CLIENTE" CHAR(3 BYTE),
   	"SEC_PERSONA_TIPO_CLIENTE" NUMBER,
   	"FECHA_INGRESO" DATE,
   	"FECHA_SALIDA" DATE,
   	"ESTADO_FID_BEN" VARCHAR2(3 BYTE),
   	"ESTADO_PARTICIPE" VARCHAR2(1 BYTE),
   	"NUMERO_CUENTA" VARCHAR2(30 BYTE));

 DROP TABLE IF EXISTS ADM_PRODUCTO;
   CREATE TABLE "ADM_PRODUCTO"
      (	"NUM_LICENCIA" NUMBER(10,0),
   	"COD_EMPRESA" VARCHAR2(15 BYTE),
   	"COD_PRODUCTO" VARCHAR2(15 BYTE),
   	"COD_TIPO_PRODUCTO" VARCHAR2(15 BYTE),
   	"COD_ESTADO_PRODUCTO" VARCHAR2(15 BYTE),
   	"NOMBRE" VARCHAR2(100 BYTE),
   	"HABILITADO_BE" VARCHAR2(1 BYTE) DEFAULT 'S',
   	"AUD_VERSION" NUMBER(10,0) DEFAULT 1,
   	"COD_MONEDA" VARCHAR2(15 BYTE),
   	"INACTIVAR_TMP" VARCHAR2(1 BYTE) DEFAULT 'N',
   	"DETALLAR_PARTICIPACION" VARCHAR2(1 BYTE) DEFAULT 'N',
   	"TIPO_ACTUALIZACION" VARCHAR2(3 BYTE) DEFAULT 'CON',
   	"HABILITADO_INFO_CTAS_BANCARIAS" VARCHAR2(1 BYTE) DEFAULT 'N',
   	"HABILITADO_INFO_INVERSIONES" VARCHAR2(1 BYTE) DEFAULT 'N',
   	"HABILITADO_INFO_CONTABLE" VARCHAR2(1 BYTE) DEFAULT 'N',
   	"HABILITADO_DOCUMENTOS" VARCHAR2(1 BYTE) DEFAULT 'N',
   	"HABILITADO_INFO_PROYECTOS_INMO" VARCHAR2(1 BYTE) DEFAULT 'N',
   	"HABILITADO_INFO_INMUEBLES" VARCHAR2(1 BYTE) DEFAULT 'N',
   	"HABILITADO_INFO_BIE_MUEBLES" VARCHAR2(1 BYTE) DEFAULT 'N',
   	"MANEJA_OPERACIONES" VARCHAR2(1 BYTE) DEFAULT 'N',
   	"HABILITADO_INFO_BIENES" VARCHAR2(1 BYTE) DEFAULT 'N',
   	"HABILITADO_MOVIMIENTOS_PARTIC" VARCHAR2(1 BYTE) DEFAULT 'N',
   	"HABILITADO_REPORTES" VARCHAR2(1 BYTE) DEFAULT 'N',
   	"FECHA_CORTE_CIERRE" DATE,
   	"GLN" NUMBER(4,0),
   	"TIEMPO_VALIDEZ_NPE" NUMBER(3,0));

 DROP TABLE IF EXISTS FID_INTENCION_APORTE_BE;
   CREATE TABLE "FID_INTENCION_APORTE_BE"
      (	"NUM_LICENCIA" NUMBER(10,0),
   	"COD_EMPRESA" VARCHAR2(8 BYTE),
   	"COD_PRODUCTO" VARCHAR2(8 BYTE),
   	"SEC_INTENCION" NUMBER,
   	"COD_PERSONA" NUMBER(8,0),
   	"CUENTA_PARTICIPE" VARCHAR2(20 BYTE),
   	"ESTADO" VARCHAR2(3 BYTE),
   	"MONTO" NUMBER(10,2),
   	"COD_MONEDA" VARCHAR2(15 BYTE),
   	"FECHA_SOLICITUD" TIMESTAMP (6),
   	"FECHA_VENCIMIENTO" TIMESTAMP (6),
   	"NPE" VARCHAR2(36 BYTE),
   	"AUD_USUARIO_INGRESO" VARCHAR2(30 BYTE),
   	"AUD_FECHA_INGRESO" TIMESTAMP (6) DEFAULT sysdate,
   	"AUD_IP_INGRESO" VARCHAR2(30 BYTE),
   	"AUD_COD_CANAL_INGRESO" VARCHAR2(8 BYTE),
   	"AUD_VERSION" NUMBER(10,0) DEFAULT 1);

 DROP TABLE IF EXISTS TRA_CFG_CREDEN_ENTIDAD_FINANC;
   CREATE TABLE "TRA_CFG_CREDEN_ENTIDAD_FINANC"
       (	"NUM_LICENCIA" NUMBER,
    	"COD_TIPO_ENTIDAD" VARCHAR2(8 BYTE),
    	"COD_ENTIDAD" VARCHAR2(8 BYTE),
    	"COD_ACCESO" VARCHAR2(100 BYTE),
    	"TOKEN_ACCESO" BLOB DEFAULT EMPTY_BLOB(),
    	"AUD_USUARIO_INGRESO" VARCHAR2(30 BYTE),
    	"AUD_FECHA_INGRESO" TIMESTAMP (6) DEFAULT sysdate,
    	"AUD_IP_INGRESO" VARCHAR2(30 BYTE),
    	"AUD_COD_CANAL_INGRESO" VARCHAR2(8 BYTE),
    	"AUD_VERSION" NUMBER(10,0) DEFAULT 1);


 DROP TABLE IF EXISTS AUD_INTERFAZ_LOG;
   CREATE TABLE "AUD_INTERFAZ_LOG"
      (	"ID" NUMBER,
   	"USUARIO" VARCHAR2(20 BYTE),
   	"OPERACION" VARCHAR2(20 BYTE),
   	"FONDO" VARCHAR2(200 BYTE),
   	"PARTICIPE" VARCHAR2(200 BYTE),
   	"TRAMA_PEDIDO" VARCHAR2(4000 BYTE),
   	"TRAMA_RESPUESTA" VARCHAR2(4000 BYTE),
   	"ESTADO" VARCHAR2(2 BYTE),
   	"MENSAJE" VARCHAR2(200 BYTE),
   	"FECHA_HORA_REG" TIMESTAMP (6));

   CREATE UNIQUE INDEX "SYS_C_SNAP$_5443IDEXPER_PK" ON "ADM_PERSONA_IDENTIFICACION" ("COD_PERSONA", "COD_TIPO_IFICACION");

   CREATE UNIQUE INDEX "PK_ADM_PRODUCTO" ON "ADM_PRODUCTO" ("NUM_LICENCIA", "COD_EMPRESA", "COD_PRODUCTO");

   CREATE UNIQUE INDEX "PK_FID_INTENCION_APORTE_BE" ON "FID_INTENCION_APORTE_BE" ("NUM_LICENCIA", "COD_EMPRESA", "COD_PRODUCTO", "SEC_INTENCION");

   CREATE UNIQUE INDEX "PK_TRA_CFG_CREDEN_ENTIDAD_FINA" ON "TRA_CFG_CREDEN_ENTIDAD_FINANC" ("NUM_LICENCIA", "COD_TIPO_ENTIDAD", "COD_ENTIDAD");

   CREATE UNIQUE INDEX "AUD_INTERFAZ_LOG_PK" ON "AUD_INTERFAZ_LOG" ("ID");

   */